services:
  # Service 1: Serveur Ollama pour les LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      # Expose le port par défaut d'Ollama (11434) sur ma machine (l'hôte)
      - "11434:11434"
    volumes:
      # Monte un volume pour rendre les modèles LLM téléchargés persistants.
      - ollama_data:/root/.ollama
    networks:
      - rag_network
    environment: 
      OLLAMA_LOAD_TIMEOUT: 10m0s 
      OLLAMA_KEEP_ALIVE: 10m0s 
    healthcheck: # healthcheck pour s'assurer qu'Ollama est prêt
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s # Temps pour le démarrage initial d'Ollama
    command: serve

  # Service 2: Base de données PostgreSQL avec l'extension pgvector, pour stocker les documents sous format vectoriel (embeddings). 
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      # Variables d'environnement pour initialiser la base de données.
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      # Expose le port de PostgreSQL (5432) sur le port 5433 de ma machine
      - "5433:5432"
    volumes:
      # Monte un volume pour rendre les données de la base persistantes.
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network
    healthcheck: # healthcheck pour s'assurer que Postgres est prêt
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Service 3: mon application RAG en python
  rag-app:
    build:
      context: ./rag_app # Le répertoire où se trouve le Dockerfile pour l'app
      dockerfile: Dockerfile
    container_name: rag_application
    environment:
      # Variables d'environnement pour l'application RAG
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_HOST: postgres_db # nom du service Docker
      POSTGRES_PORT: 5432       # Port interne de Postgres dans le conteneur
      POSTGRES_DB: rag_db     
      OLLAMA_BASE_URL: http://ollama_server:11434 
      LLM_MODEL: gemma3:4b
      EMBEDDING_MODEL: nomic-embed-text:latest 
    volumes:
      - ./rag_app:/app
    networks:
      - rag_network
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure # Redémarre en cas d'échec

# Déclaration des volumes nommés pour la persistance des données
volumes:
  ollama_data:
  postgres_data:

# Déclaration du réseau pour permettre la communication entre les conteneurs
networks:
  rag_network:
    driver: bridge